# version: "3.8"

services:
  db-postgres:
    build: .
    container_name: my-postgres-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres_data:/var/var/lib/postgresql/data

volumes:
  postgres_data:
