# Thiết lập mật khẩu để kết nối vào Redis
requirepass mysecretpassword

# Cho phép Redis lắng nghe từ mọi địa chỉ IP bên trong container
bind 0.0.0.0

# Giới hạn bộ nhớ tối đa (ví dụ 100MB)
maxmemory 100mb
maxmemory-policy allkeys-lru